allowBuilds:
  core-js: true
  esbuild: true
  simple-git-hooks: true

catalogMode: prefer

ignoreWorkspaceRootCheck: true

shellEmulator: true

trustPolicy: no-downgrade
packages:
  - playground
  - docs
  - packages/*
  - packages/fields/*
  - examples/*
catalogs:
  cli:
    '@antfu/eslint-config': ^6.2.0
    '@antfu/ni': ^27.0.1
    bumpp: ^10.3.1
    eslint: ^9.39.1
    lint-staged: ^16.2.6
    postcss: ^8.5.6
    postcss-cli: ^11.0.1
    postcss-import: ^16.1.0
    publint: ^0.3.17
    simple-git-hooks: ^2.13.1
    tsdown: ^0.16.0
    tsx: ^4.20.6
    turbo: ^2.8.3
    typescript: ^5.9.3
    vite: ^7.2.1
  docs:
    vitepress: next
  inlined:
    '@antfu/utils': ^9.3.0
  shared:
    lodash-es: ^4.17.23
  testing:
    '@vue/test-utils': ^2.4.11
    happy-dom: ^20.10.6
    tinyexec: ^1.0.2
    vitest: ^4.0.7
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/lodash-es': ^4.17.12
    '@types/node': ^24.10.0
  vue:
    '@floating-ui/dom': ^1.7.4
    '@vitejs/plugin-vue': ^6.0.4
    ant-design-vue: ^4.2.6
    vue: ^3.5.27
onlyBuiltDependencies:
  - core-js
  - esbuild
  - simple-git-hooks
