import type { DocumentSchema } from '@dragcraft/designer'

export const ecommerceSchema: DocumentSchema = {
  version: '1',
  globalConfig: {
    title: '好物精选',
    description: '小程序商城首页',
    backgroundColor: '#ffffff',
  },
  page: {
    props: { title: '好物精选' },
    style: { backgroundColor: '#ffffff' },
  },
  nodes: [
    { id: 'nav-ecommerce', type: 'navbar', props: { title: '好物精选' } },
    {
      id: 'tabbar-main',
      type: 'tab-bar',
      props: {
        tabs: [
          { label: '首页', icon: 'home' },
          { label: '分类', icon: 'category' },
          { label: '购物车', icon: 'cart' },
          { label: '我的', icon: 'user' },
        ],
        activeIndex: 0,
        backgroundColor: '#ffffff',
        activeColor: '#07c160',
        inactiveColor: '#999999',
      },
    },
    {
      id: 'floating-cart',
      type: 'floating-button',
      props: { label: '+', side: 'right', bottom: 72, sideOffset: 16, size: 52, backgroundColor: '#07c160', textColor: '#ffffff' },
    },
    {
      id: 'swiper-banner',
      type: 'swiper',
      props: {
        images: [
          'https://picsum.photos/seed/store-banner/750/300',
          'https://picsum.photos/seed/store-banner2/750/300',
          'https://picsum.photos/seed/store-banner3/750/300',
        ],
        showIndicator: true,
        height: 180,
      },
    },
    { id: 'shop-title', type: 'text', props: { content: '好物精选商城', fontSize: 20, fontWeight: 'bold', color: '#1a1a1a', textAlign: 'left' } },
    { id: 'shop-desc', type: 'text', props: { content: '精选好物，品质生活。每日上新，限时特惠！', fontSize: 13, fontWeight: 'normal', color: '#777777', textAlign: 'left' } },
    { id: 'divider-1', type: 'divider', props: { direction: 'horizontal', color: '#eeeeee', thickness: 1 } },
    { id: 'product-img', type: 'image', props: { src: 'https://picsum.photos/seed/product-1/750/400', alt: '热销商品', objectFit: 'cover', height: 200 } },
    { id: 'product-name', type: 'text', props: { content: '限量款轻奢手提包 | 头层牛皮', fontSize: 16, fontWeight: 'bold', color: '#1a1a1a', textAlign: 'left' } },
    { id: 'product-price', type: 'text', props: { content: '¥ 299.00', fontSize: 18, fontWeight: 'bold', color: '#d9363e', textAlign: 'left' } },
    { id: 'buy-btn', type: 'button', props: { text: '立即购买', type: 'button', disabled: false, size: 'large' } },
    { id: 'divider-2', type: 'divider', props: { direction: 'horizontal', color: '#eeeeee', thickness: 8 } },
    { id: 'member-title', type: 'text', props: { content: '会员登记', fontSize: 16, fontWeight: 'bold', color: '#1a1a1a', textAlign: 'left' } },
    { id: 'member-desc', type: 'text', props: { content: '注册会员即享 9 折优惠', fontSize: 13, fontWeight: 'normal', color: '#777777', textAlign: 'left' } },
    { id: 'form-name', type: 'form-input', props: { label: '姓名', placeholder: '请输入您的姓名', value: '', required: true, disabled: false } },
    { id: 'form-phone', type: 'form-input', props: { label: '手机号', placeholder: '请输入手机号码', value: '', required: true, disabled: false } },
    { id: 'form-gender', type: 'form-radio-group', props: { label: '性别', value: '', options: [{ label: '男', value: 'male' }, { label: '女', value: 'female' }], direction: 'horizontal', disabled: false } },
    { id: 'form-agree', type: 'form-checkbox', props: { label: '我已阅读并同意《会员服务条款》', checked: false, disabled: false } },
    { id: 'form-submit', type: 'button', props: { text: '提交登记', type: 'submit', disabled: false, size: 'large' } },
    { id: 'analytics-home', type: 'analytics-config', props: { eventName: 'home_view' } },
  ],
  structure: {
    root: [
      'nav-ecommerce',
      'tabbar-main',
      'floating-cart',
      'swiper-banner',
      'shop-title',
      'shop-desc',
      'divider-1',
      'product-img',
      'product-name',
      'product-price',
      'buy-btn',
      'divider-2',
      'member-title',
      'member-desc',
      'form-name',
      'form-phone',
      'form-gender',
      'form-agree',
      'form-submit',
      'analytics-home',
    ],
    containers: {},
  },
}
